### PR TITLE
feat: added configurable token ttl

### PR DESCRIPTION
**Pull request by vuurball**
**feat**: added configurable token ttl. 
**motivation**: be able to control the magic token ttl when configuring the strategy

### CODE REVIEW

**Comment by ShrihariMohan** [comment]
I was searching the docs for time to live for the token , but its in the PR.

**Comment by vuurball** [comment]
Hey @mxstbr , what do you think about this PR?

**Comment by mxstbr** [comment]
This should really just be passing through the entire`jwt.sign` options object, rather than specifically the expiresIn time. If we make that change, I'm happy to add this!

**Comment by mxstbr** [comment]
Implemented in #23 by @marcusvmsa!

**Pull request closed without merging**
